name: env_fundamentos_ambiente_virtual
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - beautifulsoup4
  - requests
  - geckodriver
  - selenium
  - pandas
  - matplotlib
  - webdriver-manager
